server:
  port: 8085
spring:
  application:
    name: bs-kafka-consumer
  cloud:
    stream:
      kafka:
        binder:
          auto-create-topics: true   # 自动创建topics
          brokers: localhost:9092
          required-acks: all
        bindings:
          sms-in-0:
            consumer:
              ackMode: MANUAL # sms手动确认消息
      bindings:

        # in-0固定 消费者需要有bean与in前的名称对应
        # log topic
        log-in-0:
          destination: log-topic
          group: log_group
          binder: kafka
#        log-out-0:
#          destination: log-topic
#          group: log_group
#          binder: kafka
        # sms-topic
        sms-in-0:
          destination: sms-topic
          group: sms_group
          binder: kafka
          consumer:
            max-attempts: 1
      # 指定消费者通道
      function:
        definition: log;sms
