spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        # log topic
        log-out-0:
          destination: log-topic
          group: log_group
          binder: kafka
        # sms-topic
        sms-out-0:
          destination: sms-topic
          group: log_group
          binder: kafka
          consumer:
            max-attempts: 1
